cache_run_c_code = 'Test does not build: Traceback (most recent call last):\n  File "/home/projects/ns-allinone-3.16/ns-3.16/.waf-1.6.11-30618c54883417962c38f5d395f83584/waflib/Tools/c_config.py", line 445, in run_c_code\n    bld.compile()\n  File "/home/projects/ns-allinone-3.16/ns-3.16/.waf-1.6.11-30618c54883417962c38f5d395f83584/waflib/Build.py", line 190, in compile\n    raise Errors.BuildError(self.producer.error)\nBuildError: Build failed\n -> task in \'testprog\' failed (exit status 1): \n\t{task 139732252863184: cxx test.cpp -> test.cpp.1.o}\n[\'/usr/bin/g++\', \'-std=c++11\', \'-flto=auto\', \'-ffat-lto-objects\', \'-flto=auto\', \'-fno-strict-aliasing\', \'-fwrapv\', \'-ffile-prefix-map=/build/python2.7-W40Ff2/python2.7-2.7.18=.\', \'-flto=auto\', \'-ffat-lto-objects\', \'-flto=auto\', \'-ffat-lto-objects\', \'-fstack-protector-strong\', \'-DNS3_ASSERT_ENABLE\', \'-DNS3_LOG_ENABLE\', \'-DPYTHONDIR="/usr/local/lib/python2.7/dist-packages"\', \'-DPYTHONARCHDIR="/usr/local/lib/python2.7/dist-packages"\', \'-DNDEBUG\', \'-D_FORTIFY_SOURCE=2\', \'../test.cpp\', \'-c\', \'-o\', \'test.cpp.1.o\']\n'
